[ALPS04982554] power: rename platform header
[Error]
mtk_thermal_platform.c:23:10:
fatal error: mach/mtk_thermal.h file not found

[Detail]
We only keep a specific platform when we run the release policy.
In the case mtk_thermal_platform.c include mt6779 headers.
That is not allowed when we only release mt6761 drivers.
This patch rename to platform header to workaorund it.

MTK-Commit-Id: 49c300d936a427c9a1bde248f3dbdf4eeb5b2eec

Test: Build and Boot
Change-Id: I5c157a899187edf095c6c42b1b43e10440d6e4e4
CR-Id: ALPS04982554
Feature:Thermal Management
Signed-off-by: Juju Sung <juju.sung@mediatek.com>