mmdvfs: Fix wrapper build error caused by wrong data type in snprintf
1. Change to %llu in snprintf for data type u64
2. Initialize 'voltage' variable

Error message:
drivers/misc/mediatek/mmdvfs/mmdvfs_wrapper.c: In function 'get_test_freq':
drivers/misc/mediatek/mmdvfs/mmdvfs_wrapper.c:267:26: error: format '%d' expects argument of type 'int', but argument 4 has type 'u64 {aka long long unsigned int}' [-Werror=format=]
      PAGE_SIZE - length, "%d)\n", steps[i]);
                          ^
drivers/misc/mediatek/mmdvfs/mmdvfs_wrapper.c:270:26: error: format '%d' expects argument of type 'int', but argument 4 has type 'u64 {aka long long unsigned int}' [-Werror=format=]
      PAGE_SIZE - length, "%d,", steps[i]);
                          ^
  CC      kernel/module.o
drivers/misc/mediatek/mmdvfs/mmdvfs_wrapper.c: In function 'mmdvfs_qos_get_freq':
drivers/misc/mediatek/mmdvfs/mmdvfs_wrapper.c:153:35: error: 'voltage' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (mmdvfs_wrapper->voltages[i] == voltage)
                                   ^

Feature: [Module]MM pipeline/MM DVFS
Change-Id: I854e74d6f26f19a4dac6a8e081ae4d0d798e70db
CR-Id: ALPS04534416
Signed-off-by: Anthony Huang <anthony.huang@mediatek.com>