[ALPS05515589] KPM: Fix unused variable build break
  error: unused variable orphan_list [-Werror,-Wunused-variable]
  make[3]: ***
  [kernel-4.19/scripts/Makefile.build:333:drivers/clk/clk.o] Error 1

MTK-Commit-Id: 2718f04e036c6ec8f8c0a6ed5f42b54dd4fb4694

Change-Id: Ibc0ac7dbbeb57816e3dd0b37d53aaa5b78b83099
CR-Id: ALPS05515589
Feature: [Module]Kernel Maintenance
Signed-off-by: Bo Ye <bo.ye@mediatek.com>