drivers: misc: mediatek: add missing includes to `apusys_dbg.h` and `charger_type.h`
* fixes the following build errors:

drivers/misc/mediatek/apusys/midware/1.1/apusys_dbg.h:12:
error: declaration of 'struct device' will not be visible outside of this function
  void apusys_dump_init(struct device *dev);
  void apusys_dump_exit(struct device *dev);

drivers/misc/mediatek/include/mt-plat/v1/charger_type.h:201:
error: declaration of 'struct device' will not be visible outside of this function
  extern bool is_usb_rdy(struct device *dev);

drivers/power/supply/mediatek/charger/mtk_charger_intf.h:641:
error: conflicting types for 'is_usb_rdy'

Change-Id: I8101968a1de49d836a705b711ab33494475cad20
Signed-off-by: rajdeep-3305 <rajdeepbiswas3305@gmail.com>